//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int pkClientID { get; set; }
        public string imenumber { get; set; }
        public string PrimaryCellNumber { get; set; }
        public string EmployeeNumber { get; set; }
        public string ClientName { get; set; }
        public string LandLine { get; set; }
        public string IDNumber { get; set; }
        public string Email { get; set; }
        public string CostCode { get; set; }
        public string WBSNumber { get; set; }
        public decimal AdminFee { get; set; }
        public string IPAddress { get; set; }
        public int fkCompanyID { get; set; }
        public int fkClientLocationID { get; set; }
        public int fkContractID { get; set; }
        public int fkClientBillingID { get; set; }
        public int fkSuburbID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ClientBilling ClientBilling { get; set; }
        public virtual ClientLocation ClientLocation { get; set; }
        public virtual Suburb Suburb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Company Company { get; set; }
    }
}
