//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyBillingLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyBillingLevel()
        {
            this.ClientBillings = new HashSet<ClientBilling>();
        }
    
        public int pkCompanyBillingLevelID { get; set; }
        public int fkCompanyGroupID { get; set; }
        public int fkBillingLevelID { get; set; }
        public decimal Amount { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual BillingLevel BillingLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientBilling> ClientBillings { get; set; }
        public virtual CompanyGroup CompanyGroup { get; set; }
    }
}
