//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataValidationProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataValidationProperty()
        {
            this.DataValidationRules = new HashSet<DataValidationRule>();
            this.DataValidationExceptions = new HashSet<DataValidationException>();
        }
    
        public int pkDataValidationPropertyID { get; set; }
        public short enDataValidationGroupName { get; set; }
        public Nullable<short> enDataValidationEntity { get; set; }
        public Nullable<short> enDataValidationProperty { get; set; }
        public string ExtDataValidationProperty { get; set; }
        public short enDataType { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataValidationRule> DataValidationRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataValidationException> DataValidationExceptions { get; set; }
    }
}
