//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataValidationException
    {
        public int pkDataValidationExceptionID { get; set; }
        public string BillingPeriod { get; set; }
        public int fkBillingProcessID { get; set; }
        public short enDataValidationGroupName { get; set; }
        public int DataValidationEntityID { get; set; }
        public int fkDataValidationPropertyID { get; set; }
        public string Message { get; set; }
        public Nullable<bool> CanApplyRule { get; set; }
        public Nullable<bool> Result { get; set; }
    
        public virtual BillingProcess BillingProcess { get; set; }
        public virtual DataValidationProperty DataValidationProperty { get; set; }
    }
}
