//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataValidationRule
    {
        public int pkDataValidationRuleID { get; set; }
        public short enValidationProcess { get; set; }
        public short enDataValidationEntity { get; set; }
        public int DataValidationEntityID { get; set; }
        public Nullable<int> fkDataValidationPropertyID { get; set; }
        public Nullable<int> fkPackageID { get; set; }
        public string ExtDataValidationProperty { get; set; }
        public short enDataValidationOperator { get; set; }
        public string DataValidationValue { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual DataValidationProperty DataValidationProperty { get; set; }
        public virtual Package Package { get; set; }
    }
}
