//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceModel()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int pkDeviceModelID { get; set; }
        public int fkDeviceMakeID { get; set; }
        public string ModelDescription { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModfiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DeviceMake DeviceMake { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
    }
}
