//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportRuleData
    {
        public int pkImportRuleDataID { get; set; }
        public short enImportSource { get; set; }
        public short enImportDestination { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsActive { get; set; }
    }
}
