//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int pkInvoiceID { get; set; }
        public Nullable<decimal> AccID { get; set; }
        public string CellNo { get; set; }
        public string EmpNo { get; set; }
        public string Service { get; set; }
        public string ImeNo { get; set; }
        public Nullable<int> fkClientID { get; set; }
        public Nullable<int> fkServiceID { get; set; }
        public string InvoicePeriod { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> CompanyDue { get; set; }
        public Nullable<decimal> PrivateDue { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public Nullable<bool> IsPeriodClosed { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
