//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInCompany
    {
        public int pkUserInCompanyID { get; set; }
        public int fkUserID { get; set; }
        public int fkCompanyID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Company Company { get; set; }
    }
}
